export const postTypes = {
  ADD_POST_REQUEST: "ADD_POST_REQUEST" as const,
  ADD_POST_SUCCESS: "ADD_POST_SUCCESS" as const,
  ADD_POST_FAILURE: "ADD_POST_FAILURE" as const,
  ADD_COMMENT_REQUEST: "ADD_COMMENT_REQUEST" as const,
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS" as const,
  ADD_COMMENT_FAILURE: "ADD_COMMENT_FAILURE" as const,
}